/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.pbs;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author administrator
 */
public class DuplicateCustomerGUI extends javax.swing.JFrame {

    File newCustomersFile;
    ArrayList<String> customerList, newCustomerList;
    
    /**
     * Creates new form DuplicateCustomerGUI
     */
    public DuplicateCustomerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uploadCustomersButton = new javax.swing.JButton();
        enterEmailButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        progressTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uploadCustomersButton.setText("Upload customers");
        uploadCustomersButton.setEnabled(false);
        uploadCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadCustomersButtonActionPerformed(evt);
            }
        });

        enterEmailButton.setText("Enter email");
        enterEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterEmailButtonActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.setEnabled(false);
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Progress");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadCustomersButton)
                    .addComponent(enterEmailButton)
                    .addComponent(runButton)
                    .addComponent(jLabel2)
                    .addComponent(progressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterEmailButton)
                .addGap(32, 32, 32)
                .addComponent(uploadCustomersButton)
                .addGap(29, 29, 29)
                .addComponent(runButton)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterEmailButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailSettingsPopup().setVisible(true);
            }
        });
        progressTextField.setText("Adding email settings");
    }//GEN-LAST:event_enterEmailButtonActionPerformed

    private void uploadCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadCustomersButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV Files", "csv");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(jPanel1);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            runButton.setEnabled(true);
            uploadCustomersButton.setEnabled(false);
            newCustomersFile = fileChooser.getSelectedFile();
        }
        progressTextField.setText("Adding customer file");
    }//GEN-LAST:event_uploadCustomersButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        String line;
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);        
        
        customerList = new ArrayList<>();
        newCustomerList = new ArrayList<>();
        try {
            progressTextField.setText("Reading master list");
            BufferedReader fileReader = new BufferedReader(new FileReader("C:\\Customers\\Master.csv"));
            fileReader.readLine();
            while ((line = fileReader.readLine()) != null) {
                String[] customer = line.split(",");
                customerList.add(customer[0]);
            }
            
            progressTextField.setText("Reading new list");
            fileReader = new BufferedReader(new FileReader(newCustomersFile));
            fileReader.readLine();
            while ((line = fileReader.readLine()) != null) {
                String[] customer = line.split(",");
                if(!(customerList.contains(customer[0]))){
                    customerList.add(line);
                    newCustomerList.add(line);
                }
            }
            fileReader.close();
            
            progressTextField.setText("Writing customer lists");
            Writer newCustomerFileWriter = new FileWriter("C:\\Customers\\New customers " + date + ".csv");
            Writer masterCustomerFileWriter = new FileWriter("C:\\Customers\\Master.csv", true);
            newCustomerFileWriter.write("Email\n");
            for(String email:newCustomerList){
                newCustomerFileWriter.write(email + "\n");
                masterCustomerFileWriter.write("\n" + email + "," + date);
            }
            newCustomerFileWriter.flush();
            masterCustomerFileWriter.flush();
            
            newCustomerFileWriter.close();
            masterCustomerFileWriter.close();
            progressTextField.setText("Sending email");
            EmailSender sender = new EmailSender();
            sender.sendEmail();
            progressTextField.setText("exiting");
            System.exit(0);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DuplicateCustomerGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DuplicateCustomerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_runButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DuplicateCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DuplicateCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DuplicateCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DuplicateCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DuplicateCustomerGUI().setVisible(true);
            }
        });
    }

    public static void setCustomerButton(Boolean enabled) {
        uploadCustomersButton.setEnabled(enabled);
    }

    public static void setEnterEmailButton(Boolean enabled) {
        enterEmailButton.setEnabled(enabled);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton enterEmailButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField progressTextField;
    private javax.swing.JButton runButton;
    public static javax.swing.JButton uploadCustomersButton;
    // End of variables declaration//GEN-END:variables
}
