/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.pbs;

import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JOptionPane;
import static main.java.com.pbs.DuplicateCustomerGUI.setCustomerButton;
import static main.java.com.pbs.DuplicateCustomerGUI.setEnterEmailButton;
import static main.java.com.pbs.EmailSender.setFrom;
import static main.java.com.pbs.EmailSender.setSMTP_EMAIL;
import static main.java.com.pbs.EmailSender.setSMTP_PASSWORD;
import static main.java.com.pbs.EmailSender.setTo;

/**
 *
 * @author administrator
 */
public class EmailSettingsPopup extends javax.swing.JFrame {

    /**
     * Creates new form EmailSettingsPopup
     */
    public EmailSettingsPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailPopupCancelButton = new javax.swing.JButton();
        EmailAddressTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        EmailPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        emailPopupOkButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        emailToTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emailPopupCancelButton.setText("Cancel");
        emailPopupCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPopupCancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Email address");

        jLabel2.setText("Password");

        emailPopupOkButton.setText("Ok");
        emailPopupOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPopupOkButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Email to");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(emailPopupOkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailPopupCancelButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmailPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(EmailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailPopupOkButton)
                    .addComponent(emailPopupCancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailPopupCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPopupCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_emailPopupCancelButtonActionPerformed

    private void emailPopupOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPopupOkButtonActionPerformed
        if (!checkValidEmail()) {
            JOptionPane.showMessageDialog(null, "The email address is not valid");
        } else if (!(EmailPasswordField.getPassword().length > 0)) {
            JOptionPane.showMessageDialog(null, "Please enter a password");
        } else {
            setSMTP_EMAIL(EmailAddressTextField.getText());
            setFrom(EmailAddressTextField.getText());
            setSMTP_PASSWORD(EmailPasswordField.getPassword());
            setTo(emailToTextField.getText());
            this.dispose();
            setCustomerButton(true);
            setEnterEmailButton(false);
        }
    }//GEN-LAST:event_emailPopupOkButtonActionPerformed

    public Boolean checkValidEmail() {
        boolean result = true;
        try {
            InternetAddress email = new InternetAddress(EmailAddressTextField.getText());
            InternetAddress emailTo = new InternetAddress(emailToTextField.getText());
            email.validate();
            emailTo.validate();
        } catch (AddressException ex) {
            result = false;
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailAddressTextField;
    private javax.swing.JPasswordField EmailPasswordField;
    private javax.swing.JButton emailPopupCancelButton;
    private javax.swing.JButton emailPopupOkButton;
    private javax.swing.JTextField emailToTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
